//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SISGFRAN.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opcion
    {
        public Opcion()
        {
            this.OpcionPerfil = new HashSet<OpcionPerfil>();
        }
    
        public int Id { get; set; }
        public int AplicacionId { get; set; }
        public Nullable<int> PadreId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> NivelPadre { get; set; }
        public string Imagen { get; set; }
        public string Controler { get; set; }
        public string Accion { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Observacion { get; set; }
        public byte Estado { get; set; }
        public Nullable<int> AuditoriaUC { get; set; }
        public Nullable<int> AuditoriaUM { get; set; }
        public System.DateTime AuditoriaFC { get; set; }
        public Nullable<System.DateTime> AuditoriaFM { get; set; }
    
        public virtual Aplicacion Aplicacion { get; set; }
        public virtual ICollection<OpcionPerfil> OpcionPerfil { get; set; }
    }
}
