//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SISGFRAN.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public Solicitud()
        {
            this.Entrevista = new HashSet<Entrevista>();
            this.ReporteEvaluacion = new HashSet<ReporteEvaluacion>();
            this.Solicitante = new HashSet<Solicitante>();
        }
    
        public int Id { get; set; }
        public string NumSolicitud { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string CiudadInteres { get; set; }
        public string UbigeoCiudadInteres { get; set; }
        public Nullable<decimal> MontoCapital { get; set; }
        public string FuenteFinanciamiento { get; set; }
        public Nullable<System.DateTime> FechaInicioOperacion { get; set; }
        public Nullable<int> LocalDisponible { get; set; }
        public Nullable<int> CondicionLocalId { get; set; }
        public string UbigeoLocal { get; set; }
        public string DireccionLocal { get; set; }
        public Nullable<int> TipoUbicacionLocalId { get; set; }
        public string ReferenciaComercial { get; set; }
        public string ReferenciaBancaria { get; set; }
        public Nullable<int> Estado { get; set; }
        public int AuditoriaUC { get; set; }
        public Nullable<int> AuditoriaUM { get; set; }
        public System.DateTime AuditoriaFC { get; set; }
        public Nullable<System.DateTime> AuditoriaFM { get; set; }
    
        public virtual ICollection<Entrevista> Entrevista { get; set; }
        public virtual ICollection<ReporteEvaluacion> ReporteEvaluacion { get; set; }
        public virtual ICollection<Solicitante> Solicitante { get; set; }
    }
}
