//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SISGFRAN.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitante
    {
        public int Id { get; set; }
        public int TipoSolicitanteId { get; set; }
        public int SolicitudId { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> TipoDocumentoId { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<int> SexoId { get; set; }
        public Nullable<int> EstadoCivilId { get; set; }
        public Nullable<System.DateTime> FechaIniCargoAct { get; set; }
        public Nullable<System.DateTime> FechaFinCargoAct { get; set; }
        public string NombreJefeDirecto { get; set; }
        public string TelefonoJefeDirecto { get; set; }
        public Nullable<System.DateTime> FechaConstitucion { get; set; }
        public string ActividadEconomica { get; set; }
        public Nullable<int> NumeroEmpleados { get; set; }
        public Nullable<decimal> MontoIngresosAnuales { get; set; }
        public string UbigeoDireccion { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string InstitucionEducativa { get; set; }
        public string TituloObtenido { get; set; }
        public Nullable<int> DuracionEstudios { get; set; }
        public string Idiomas { get; set; }
        public string Empresa { get; set; }
        public string Cargo { get; set; }
        public Nullable<decimal> MontoIngresosMes { get; set; }
        public Nullable<decimal> MontoGastosMes { get; set; }
        public string Observacion { get; set; }
        public int AuditoriaUC { get; set; }
        public Nullable<int> AuditoriaUM { get; set; }
        public System.DateTime AuditoriaFC { get; set; }
        public Nullable<System.DateTime> AuditoriaFM { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<bool> FueAprobado { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
    }
}
