//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SISGFRAN.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_local
    {
        public tb_local()
        {
            this.tb_reclamo = new HashSet<tb_reclamo>();
            this.tb_evaluacionProcedimiento = new HashSet<tb_evaluacionProcedimiento>();
            this.tb_sugerencia = new HashSet<tb_sugerencia>();
        }
    
        public int id { get; set; }
        public int franquiciaId { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaApertura { get; set; }
        public int localId { get; set; }
        public string responsable { get; set; }
        public int usuarioId { get; set; }
        public int distritoId { get; set; }
        public string direccion { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public int auditoriaUC { get; set; }
        public Nullable<int> auditoriaUM { get; set; }
        public System.DateTime auditoriaFC { get; set; }
        public Nullable<System.DateTime> auditoriaFM { get; set; }
        public string email { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<tb_reclamo> tb_reclamo { get; set; }
        public virtual tb_distrito tb_distrito { get; set; }
        public virtual ICollection<tb_evaluacionProcedimiento> tb_evaluacionProcedimiento { get; set; }
        public virtual tb_franquicia tb_franquicia { get; set; }
        public virtual ICollection<tb_sugerencia> tb_sugerencia { get; set; }
    }
}
