//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SISGFRAN.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sugerencia
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public string prioridad { get; set; }
        public string comentario { get; set; }
        public int localId { get; set; }
        public int empleadoId { get; set; }
        public Nullable<int> evaluacionProcDetalleId { get; set; }
        public int procedimientoId { get; set; }
        public int estado { get; set; }
        public int auditoriaUC { get; set; }
        public Nullable<int> auditoriaUM { get; set; }
        public System.DateTime auditoriaFC { get; set; }
        public Nullable<System.DateTime> auditoriaFM { get; set; }
    
        public virtual tb_local tb_local { get; set; }
        public virtual tb_empleado tb_empleado { get; set; }
    }
}
